"""empty message

Revision ID: 2b921bb496b4
Revises: b30f819e2528
Create Date: 2018-03-01 14:48:36.585719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b921bb496b4'
down_revision = 'b30f819e2528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_subject', table_name='task')
    op.create_index(op.f('ix_task_subject'), 'task', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_subject'), table_name='task')
    op.create_index('ix_task_subject', 'task', ['subject'], unique=True)
    # ### end Alembic commands ###
