"""tasks table

Revision ID: 68615982f658
Revises: 
Create Date: 2018-02-07 11:34:20.528228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68615982f658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('Critical', 'Usual', 'Important', name='prioritytype'), nullable=True),
    sa.Column('status', sa.Enum('Done', 'InWork', name='tasktype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_subject'), 'task', ['subject'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_subject'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
