"""empty message

Revision ID: b30f819e2528
Revises: 
Create Date: 2018-03-01 10:50:58.401062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30f819e2528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'usual', 'important', name='prioritytype'), nullable=True),
    sa.Column('status', sa.Enum('done', 'inwork', name='tasktype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_subject'), 'task', ['subject'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_subject'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
